### ISSUE TITLE
sudo npm install phantomjs2 -g

### ISSUE THREAD

**Issue by knoxcard** [gskachkov/karma-phantomjs2-launcher#11]
sudo npm install phantomjs2 -g
npm WARN deprecated npmconf@2.1.1: this package has been reintegrated into npm and is now out of date with respect to npm
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
/usr/local/bin/phantomjs -> /usr/local/lib/node_modules/phantomjs2/bin/phantomjs

> phantomjs2@2.2.0 install /usr/local/lib/node_modules/phantomjs2
> node install.js

Looks like an `npm install -g`; unable to check for already installed version.
invalid config loglevel="notice"
/usr/local/lib/node_modules/phantomjs2/phantomjs is not writable: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/phantomjs2/phantomjs'
Download already available at /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
Extracting tar contents (via spawned process)
Phantom installation failed { Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/phantomjs2/lib/phantom'
    at Object.fs.mkdirSync (fs.js:891:18)
    at sync (/usr/local/lib/node_modules/phantomjs2/node_modules/mkdirp/index.js:71:13)
    at Function.sync (/usr/local/lib/node_modules/phantomjs2/node_modules/mkdirp/index.js:77:24)
    at copyIntoPlace (/usr/local/lib/node_modules/phantomjs2/install.js:282:10)
    at Promise._successFn (/usr/local/lib/node_modules/phantomjs2/install.js:72:12)
    at Promise._call (/usr/local/lib/node_modules/phantomjs2/node_modules/kew/kew.js:373:13)
    at Promise._withInput (/usr/local/lib/node_modules/phantomjs2/node_modules/kew/kew.js:333:25)
    at Promise.resolve (/usr/local/lib/node_modules/phantomjs2/node_modules/kew/kew.js:105:27)
    at /usr/local/lib/node_modules/phantomjs2/install.js:274:18
    at ChildProcess.exithandler (child_process.js:262:7)
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path: '/usr/local/lib/node_modules/phantomjs2/lib/phantom' } Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/phantomjs2/lib/phantom'
    at Object.fs.mkdirSync (fs.js:891:18)
    at sync (/usr/local/lib/node_modules/phantomjs2/node_modules/mkdirp/index.js:71:13)
    at Function.sync (/usr/local/lib/node_modules/phantomjs2/node_modules/mkdirp/index.js:77:24)
    at copyIntoPlace (/usr/local/lib/node_modules/phantomjs2/install.js:282:10)
    at Promise._successFn (/usr/local/lib/node_modules/phantomjs2/install.js:72:12)
    at Promise._call (/usr/local/lib/node_modules/phantomjs2/node_modules/kew/kew.js:373:13)
    at Promise._withInput (/usr/local/lib/node_modules/phantomjs2/node_modules/kew/kew.js:333:25)
    at Promise.resolve (/usr/local/lib/node_modules/phantomjs2/node_modules/kew/kew.js:105:27)
    at /usr/local/lib/node_modules/phantomjs2/install.js:274:18
    at ChildProcess.exithandler (child_process.js:262:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! phantomjs2@2.2.0 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the phantomjs2@2.2.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-07-23T17_08_15_111Z-debug.log

**Comment by gskachkov** [comment]
@knoxcard Thanks for the message. 
But we depreciate current project, please use karma-phantomjs-launcher, that supports phantomjs@2, instead.
